### ISSUE TITLE
[BUG] Expected double-quoted property name in JSON at position 283

### ISSUE THREAD

**Issue by capybarahero** [0x80/isolate-package#2]
Hi @0x80, thanks for investigating this problem and creating this package.

I tried to use it with Firebase Functions and a "shared-library" within a PNPM monorepo, but I've stumbled on the following issue when running  `ISOLATE_CONFIG_LOG_LEVEL=debug npx isolate`: 

```
debug Attempting to load config from /<path>/monorepo/firebase-project/functions/isolate.config.json
debug Using configuration: {
  buildDirName: undefined,
  includeDevDependencies: false,
  isolateDirName: 'isolate',
  logLevel: 'info',
  targetPackagePath: undefined,
  tsconfigPath: './tsconfig.json',
  workspacePackages: undefined,
  workspaceRoot: '../..'
}
error SyntaxError: Expected double-quoted property name in JSON at position 283
    at JSON.parse (<anonymous>)
    at readTypedJson (file:///<path>/monorepo/node_modules/.pnpm/isolate-package@1.0.1/node_modules/isolate-package/src/utils/json.ts:14:21)
    at getBuildOutputDir (file:///<path>/monorepo/node_modules/.pnpm/isolate-package@1.0.1/node_modules/isolate-package/src/helpers/get-build-output-dir.ts:21:22)
    at start (file:///<path>/monorepo/node_modules/.pnpm/isolate-package@1.0.1/node_modules/isolate-package/src/index.ts:46:26)
```

Note: I have installed the packaged under the Firebase functions folder.

**Comment by 0x80** [comment]
@capybarahero That looks to me like it might be a JSON parsing error. Could you share your config file?

**Comment by 0x80** [comment]
@capybarahero Thanks for reporting. I haven't been able to reproduce the issue. I suspect the JSON parse error might come from your tsconfig file. If `isolate.config.json` is not found, the process will look for `tsconfig.json` to figure out what your build output directory is. 

Could you share the contents of your tsconfig file?

The other options you are setting are the same as the defaults, so you could leave them out. This should be enough for your setup:

```json
{
  "buildDirName": "lib",
  "logLevel": "debug"
}
``` 

The issue with pnpm pack will probably also happen with npm pack. I added to the readme that a version string is required in order for pack to work.

The `Error: ENOENT: no such file or directory` is  probably because the system can not find the packed file somehow. I have changed the debug logging to use absolute paths for the pack/unpack section. 

This is published as 1.0.2 so please give that a try. 

If there is an error, the __tmp directory is not cleaned up, so you can inspect it.

**Comment by 0x80** [comment]
In 1.0.3 I have added clear errors for any failure of reading json or yaml files.

**Comment by 0x80** [comment]
Ah glad you found it! I will add a check on the stdout result to see if it is a filepath, and if not log it and throw an error
