### ISSUE TITLE
Google App Engine usage?

### ISSUE THREAD

**Issue by maelp** [0x80/isolate-package#36]
Very cool!

I have the same issue where I tried to isolate my local monorepo package manually and bundle them with webpack to deploy an expressjs API using some local monorepo shared libs on Google App Engine

how would I use isolate-package to do the same?

**Comment by 0x80** [comment]
If you share code with steps to reproduce your problem, I might have a look, but I don't know what your problem is and I don't know the setup, and I am not very familiar with app engine. 

Like I replied in your other issue, the isolate result is basically a standalone nodejs app. How you deploy that (and if you even need an isolated output) is dependent on the platform. I can't possibly help everyone that wants to deploy something to some platform..
