### ISSUE TITLE
Failing to pack with PNPM

### ISSUE THREAD

**Issue by pwalczyszyn** [0x80/isolate-package#56]
Any idea where I can look for cause of this error?

![image](https://github.com/0x80/isolate-package/assets/368561/ae37f7e9-c9aa-4841-b6e9-fee34312600e)

**Comment by 0x80** [comment]
I haven't seen this before. But I plan to do an update soon, so I will try to improve the error logging so that it displays more context.

What OS are you on?

It might somehow be related to your file structure. It seems frontend and backend are registered as packages in the root, but also packages is a subfolder with packages in the root. That is not how monorepos are typically structured. 

Nested structures are not supported AFAIK. But by turborepo and not by isolate-package.

I would advise to move frontend and backend also in some sort of packages folder.

I usually use apps, services and packages, where apps and services are packages that are deployed or executed and packages are shared libraries.

**Comment by pwalczyszyn** [comment]
I'm on Mac, and I have same error when I moved `backend` and `frontend` under `apps` folder.

**Comment by 0x80** [comment]
Hmm 🤔 

Could try executing the `pnpm pack` command, with the parameter as given in your screenshot, from one of your packages directly?

**Comment by 0x80** [comment]
@mathieu-bour You also ran into this issue? I'm still not sure what causes this. If you have additional info or ideas please share.

**Comment by 0x80** [comment]
@pwalczyszyn I will close this issue for now. Feel free to re-open it if you have additional info.
