### ISSUE TITLE
Add support for pnpm v9

### ISSUE THREAD

**Issue by matallui** [0x80/isolate-package#71]
After upgrading to pnpm v9, the `isolate` script is now failing. Here's what I see in the logs:

```
i  functions: Start isolating the source folder...
info Generating PNPM lockfile...
i  functions: +++ Failed to isolate: Failed to generate lockfile: value.startsWith is not a function
```

I know that the lockfile format has changed in PNPM v9. Could it be related to that?

**Comment by 0x80** [comment]
I noticed this too yesterday. The imported pnpm functions do not seem to be compatible with v9. If the v9 logic is not backwards compatible with v8 it might be tricky to solve because we can not link two versions of pnpm in the dependencies. 

Possibly we could then just release a v2 of this library that is only compatible with v9 of pnpm.

I don't expect to work on this in the coming days or even weeks, so I suggest to stick with v8 for now.

**Comment by vajahath** [comment]
I was about to open this issue.

**Comment by 0x80** [comment]
It seems you can install 2 versions of the same dependency. That means I should be able to use the pnpm lockfile handling functions from v8 next to v9, and that would make it possible to support v9 while staying backwards compatible with v8.

I will try to allocate some time for this soon.

**Comment by 0x80** [comment]
Support was just added in 1.14.0. 

I will now adopt the firebase-tools-with-isolate fork to include it.
